// Hoods Phaser world v0.5 — quests, Mara, Ashwood and Grove Warden.
(() => {
const QKEY="hoods-phaser-quest-v05", AKEY="hoods-phaser-ashwood-v05";
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||"null")||f}catch{return f}};
const q=read(QKEY,{accepted:false,kills:{rat:0,slime:0,thug:0},claimed:false,roadAccepted:false,thugKills:0,roadClaimed:false});
q.kills={rat:0,slime:0,thug:0,...(q.kills||{})};
const a=read(AKEY,{bossDefeated:false,kills:0,loot:{"Ashwood Fang":0,"Charred Token":0,"Warden Crest":0}});a.loot={"Ashwood Fang":0,"Charred Token":0,"Warden Crest":0,...(a.loot||{})};
const saveQ=()=>localStorage.setItem(QKEY,JSON.stringify(q)),saveA=()=>localStorage.setItem(AKEY,JSON.stringify(a));
window.HoodsWorld={install(scene,api){
  let modal=false,attackAt=0,playerHp=api.getHp();
  const objective=scene.add.text(14,46,"",{fontFamily:"monospace",fontSize:"11px",color:"#f1e6c9",backgroundColor:"#0a0c08bb",padding:{x:8,y:6}}).setScrollFactor(0).setDepth(90);
  const questReady=()=>q.kills.rat>0&&q.kills.slime>0&&q.kills.thug>0;
  const updateObjective=()=>{let t="";if(!q.accepted)t="MARA · A CONTRACT AWAITS";else if(!q.claimed)t=`FIRST BLOOD · RAT ${Math.min(1,q.kills.rat)}/1 · SLIME ${Math.min(1,q.kills.slime)}/1 · THUG ${Math.min(1,q.kills.thug)}/1`;else if(!q.roadAccepted)t="RETURN TO MARA · ROAD EAST";else if(!q.roadClaimed)t=`ROAD EAST · WILD THUG ${Math.min(2,q.thugKills)}/2`;else if(!a.bossDefeated)t="ASHWOOD HUNT · DEFEAT GROVE WARDEN";else t="GROVE WARDEN DEFEATED · WARDEN CREST ACQUIRED";objective.setText(t)};
  const dialog=document.getElementById("pDialogue"),title=document.getElementById("pDialogueTitle"),body=document.getElementById("pDialogueBody"),action=document.getElementById("pDialogueAction");
  const close=()=>{modal=false;dialog.hidden=true};document.getElementById("pDialogueClose")?.addEventListener("click",close);
  const open=(h,html,label,fn)=>{modal=true;title.textContent=h;body.innerHTML=html;action.textContent=label;action.onclick=()=>{fn?.();close();updateObjective()};dialog.hidden=false};
  const mara=()=>{if(!q.accepted)return open("Mara the Warden","<p>The Wilds are getting bold. Kill one Bog Rat, one Mire Slime and one Wild Thug.</p>","ACCEPT FIRST BLOOD",()=>{q.accepted=true;saveQ()});if(!q.claimed){if(!questReady())return open("First Blood",`<p>Rat ${Math.min(1,q.kills.rat)}/1 · Slime ${Math.min(1,q.kills.slime)}/1 · Thug ${Math.min(1,q.kills.thug)}/1</p>`,"KEEP HUNTING");return open("First Blood complete","<p>Clean work. Take 30 Coins. I have another road for you.</p>","CLAIM +30 COINS",()=>{q.claimed=true;api.addCoins(30);saveQ()})}if(!q.roadAccepted)return open("Road East","<p>Ashwood is sealed. Bring down two Wild Thugs and I will open the eastern trail.</p>","ACCEPT ROAD EAST",()=>{q.roadAccepted=true;saveQ()});if(!q.roadClaimed){if(q.thugKills<2)return open("Road East",`<p>Wild Thugs defeated: ${q.thugKills}/2</p>`,"KEEP HUNTING");return open("Road East complete","<p>The eastern seal is yours. Ashwood Trail is now open.</p>","UNLOCK ASHWOOD",()=>{q.roadClaimed=true;api.unlockAshwood();saveQ()})}return open("Mara the Warden",a.bossDefeated?"<p>The Grove Warden has fallen. The crest will matter later.</p>":"<p>Ashwood is open. Find the Grove Warden and end it.</p>","CLOSE")};
  const mobs=[
    {kind:"wolf",name:"Thorn Wolf",x:1565,y:620,hp:70,attack:12,speed:78,coins:24,xp:22,drop:"Ashwood Fang",chance:.5,color:0x6f6449},
    {kind:"bandit",name:"Ash Bandit",x:1645,y:845,hp:105,attack:16,speed:64,coins:34,xp:34,drop:"Charred Token",chance:.35,color:0x4e4033},
    {kind:"warden",name:"Grove Warden",x:1730,y:690,hp:190,attack:20,speed:50,coins:75,xp:70,drop:"Warden Crest",chance:1,color:0x4d5a3f,boss:true}
  ].map(m=>({...m,maxHp:m.hp,sx:m.x,sy:m.y,alive:!(m.boss&&a.bossDefeated),attackAt:0,respawnAt:0}));
  mobs.forEach(m=>{const c=scene.add.container(m.x,m.y).setDepth(5);c.add(scene.add.rectangle(0,13,m.boss?40:30,7,0x000000,.25));c.add(scene.add.rectangle(0,0,m.boss?38:28,m.boss?42:30,m.color).setStrokeStyle(2,0x29241d));c.bg=scene.add.rectangle(0,m.boss?-34:-28,m.boss?64:46,5,0x331c18);c.bar=scene.add.rectangle(-(m.boss?32:23),m.boss?-34:-28,m.boss?64:46,5,m.boss?0xb9ef5a:0xc95f42).setOrigin(0,.5);c.add([c.bg,c.bar]);c.add(scene.add.text(0,m.boss?-50:-40,m.boss?"★ GROVE WARDEN ★":m.name,{fontFamily:"monospace",fontSize:m.boss?"11px":"10px",color:"#efe3bf",fontStyle:"bold"}).setOrigin(.5));m.view=c;if(!m.alive)c.setVisible(false)});
  const inAsh=()=>api.ashwoodUnlocked()&&scene.player.x>1480;
  const respawn=m=>{if(m.boss&&a.bossDefeated)return;m.alive=true;m.hp=m.maxHp;m.x=m.sx;m.y=m.sy;m.view.setPosition(m.x,m.y).setVisible(true);m.bar.width=m.boss?64:46};
  const attack=()=>{if(!inAsh()||modal)return false;const now=scene.time.now;if(now<attackAt)return true;attackAt=now+430;const alive=mobs.filter(m=>m.alive).sort((x,y)=>Phaser.Math.Distance.Between(scene.player.x,scene.player.y,x.x,x.y)-Phaser.Math.Distance.Between(scene.player.x,scene.player.y,y.x,y.y));const m=alive[0];if(!m||Phaser.Math.Distance.Between(scene.player.x,scene.player.y,m.x,m.y)>92){api.say("No Ashwood enemy in range");return true}const dmg=Math.max(1,api.stats().attack+3+Phaser.Math.Between(0,3));m.hp=Math.max(0,m.hp-dmg);m.bar.width=(m.boss?64:46)*(m.hp/m.maxHp);scene.tweens.add({targets:m.view,alpha:.25,duration:60,yoyo:true});if(m.hp<=0){m.alive=false;m.view.setVisible(false);if(m.boss){a.bossDefeated=true;a.loot["Warden Crest"]++;api.say("GROVE WARDEN DEFEATED · WARDEN CREST",2200)}else{m.respawnAt=now+Phaser.Math.Between(6500,9000);if(Math.random()<=m.chance+Math.max(0,api.stats().luck-1)*.015)a.loot[m.drop]++;api.say(`${m.name} defeated · +${m.coins} Coins`)}a.kills++;api.addCoins(m.coins);api.addXp(m.xp);saveA();api.renderInventory();updateObjective()}return true};
  const onWildKill=(m)=>{if(!q.accepted)return;if(m.kind in q.kills)q.kills[m.kind]++;if(q.roadAccepted&&!q.roadClaimed&&m.kind==="thug")q.thugKills=Math.min(2,q.thugKills+1);saveQ();updateObjective()};
  const interact=()=>{if(Phaser.Math.Distance.Between(scene.player.x,scene.player.y,scene.mara.x,scene.mara.y)<120){mara();return true}return false};
  const update=dt=>{if(!inAsh()||modal)return;const now=scene.time.now;mobs.forEach(m=>{if(!m.alive){if(!m.boss&&now>=m.respawnAt)respawn(m);return}const d=Phaser.Math.Distance.Between(scene.player.x,scene.player.y,m.x,m.y);if(d>42&&d<(m.boss?300:225)){const ang=Phaser.Math.Angle.Between(m.x,m.y,scene.player.x,scene.player.y);m.x=Phaser.Math.Clamp(m.x+Math.cos(ang)*m.speed*dt,1505,1760);m.y=Phaser.Math.Clamp(m.y+Math.sin(ang)*m.speed*dt,500,1050);m.view.setPosition(m.x,m.y)}if(d<=45&&now>=m.attackAt){m.attackAt=now+(m.boss?850:1050);playerHp=api.getHp();const dmg=Math.max(1,m.attack-Math.floor(api.stats().defense/2));api.setHp(playerHp-dmg);api.say(`${m.name} hits · -${dmg} HP`);if(api.getHp()<=0){scene.player.setPosition(900,760);api.setHp(api.stats().hp);mobs.filter(x=>!x.boss).forEach(respawn);api.say("Ashwood defeated you · returned to Town",1800)}}})};
  const appendInventory=root=>{Object.entries(a.loot).filter(([,n])=>n>0).forEach(([name,n])=>{const d=document.createElement("div");d.className="p-item";d.innerHTML=`<span><b>${name}</b><small>ASHWOOD DROP</small></span><strong>×${n}</strong>`;root.appendChild(d)})};
  updateObjective();return{update,interact,attack,onWildKill,isModal:()=>modal,close,appendInventory};
}};
})();