// Hoods Phaser migration v0.4 — full Phaser runtime with mobile controls.
(() => {
const WORLD_W=1800,WORLD_H=1200,SAVE_KEY="hoods-town-v02",WORLD_SAVE_KEY="hoods-world-v05";
const BASE={hp:100,attack:5,defense:3,speed:5,luck:1};
const ITEMS=[{id:"iron-sword",name:"Iron Sword",slot:"weapon",price:35,rarity:"UNCOMMON",stats:{attack:5}},{id:"iron-helmet",name:"Iron Helmet",slot:"helmet",price:25,rarity:"UNCOMMON",stats:{defense:2}},{id:"leather-armor",name:"Leather Armor",slot:"armor",price:30,rarity:"COMMON",stats:{hp:10,defense:3}},{id:"wooden-shield",name:"Wooden Shield",slot:"shield",price:20,rarity:"COMMON",stats:{defense:2}},{id:"ranger-boots",name:"Ranger Boots",slot:"boots",price:18,rarity:"RARE",stats:{speed:2,luck:1}}];
const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||"null")||f}catch{return f}},raw=read(SAVE_KEY,{}),world=read(WORLD_SAVE_KEY,{});
const state={coins:Number.isFinite(raw.coins)?raw.coins:120,owned:new Set(raw.owned||[]),equipped:{helmet:null,armor:null,weapon:null,shield:null,boots:null,...(raw.equipped||{})}};
const valid=new Set(ITEMS.map(i=>i.id));Object.keys(state.equipped).forEach(k=>{if(!valid.has(state.equipped[k])||!state.owned.has(state.equipped[k]))state.equipped[k]=null});
const save=()=>localStorage.setItem(SAVE_KEY,JSON.stringify({coins:state.coins,owned:[...state.owned],equipped:state.equipped})),item=id=>ITEMS.find(i=>i.id===id);
const stats=()=>{const s={...BASE};Object.values(state.equipped).forEach(id=>{const it=item(id);if(it)Object.entries(it.stats).forEach(([k,v])=>s[k]=(s[k]||0)+v)});const lv=window.HoodsProgression?.state?.level||1;s.hp+=(lv-1)*5;s.attack+=Math.floor((lv-1)/2);return s},bonus=it=>Object.entries(it.stats).map(([k,v])=>`+${v} ${k.toUpperCase()}`).join(" · ");
class TownScene extends Phaser.Scene{
constructor(){super("TownScene");this.touch={up:false,down:false,left:false,right:false}}
create(){this.physics.world.setBounds(0,0,WORLD_W,WORLD_H);this.cameras.main.setBounds(0,0,WORLD_W,WORLD_H);this.drawWorld();this.createSolids();this.createPlayer();this.createNpcs();this.createControls();this.createUi();this.cameras.main.startFollow(this.player,true,.1,.1);this.cameras.main.setRoundPixels(true);this.combat=window.HoodsCombat?.install(this,{stats,refreshHud:()=>this.refreshHud(),addCoins:n=>{state.coins+=n;save()},renderInventory:()=>this.renderInventory(),modalOpen:()=>!this.shop.hidden||!this.inventory.hidden});this.bindTouchControls();this.refreshHud()}
drawWorld(){const g=this.add.graphics();g.fillStyle(0x6d8d45).fillRect(0,0,WORLD_W,WORLD_H);for(let x=0;x<WORLD_W;x+=48)for(let y=0;y<WORLD_H;y+=48){const n=((x/48)*17+(y/48)*31)%5;if(n===0)g.fillStyle(0x668440,.75).fillRect(x,y,48,48);else if(n===1)g.fillStyle(0x72934a,.5).fillRect(x,y,48,48)}g.fillStyle(0x315a32,.7).fillRect(0,0,WORLD_W,260);g.fillStyle(0x8a8678).fillRect(805,0,190,WORLD_H).fillRect(0,670,WORLD_W,180);g.fillStyle(0x466f83).fillRect(1420,430,250,160);this.building(g,345,360,290,190,"INN");this.building(g,760,330,260,190,"BANK");this.building(g,1110,610,250,170,"OLD BRAM'S SHOP");g.fillStyle(0x5c4430).fillRect(810,285,24,100).fillRect(966,285,24,100);g.fillStyle(0x3a3028).fillRect(830,295,140,18);g.fillStyle(0x493724).fillRect(1435,650,18,210).fillRect(1463,650,18,210);if(!world.ashwoodUnlocked)for(let y=668;y<842;y+=26)g.fillStyle(0x6f4d2e).fillRect(1440,y,36,8);[[160,180],[280,220],[420,140],[1450,180],[1580,250],[1660,430],[190,910],[330,1010],[1510,930],[1650,1020],[180,520],[1600,650],[520,1040],[1360,1060],[570,170],[1260,180]].forEach(([x,y])=>this.tree(g,x,y));const st={fontFamily:"monospace",fontSize:"12px",color:"#d8c697",fontStyle:"bold"};this.add.text(900,265,"THE WILDS — OPEN · SPACE/F ATTACK",st).setOrigin(.5);this.add.text(1458,625,world.ashwoodUnlocked?"ASHWOOD TRAIL — OPEN":"ASHWOOD TRAIL — LOCKED",st).setOrigin(.5)}
building(g,x,y,w,h,label){g.fillStyle(0x6f5337).fillRect(x,y+46,w,h-46);g.fillStyle(0x342c27).fillRect(x-10,y+28,w+20,24);g.fillStyle(0x7b3e32).fillTriangle(x-14,y+35,x+w/2,y-20,x+w+14,y+35);g.fillStyle(0xd0a25d).fillRect(x+w/2-22,y+h-64,44,64);this.add.text(x+w/2,y+68,label,{fontFamily:"monospace",fontSize:"13px",color:"#f0dcae",fontStyle:"bold"}).setOrigin(.5,0)}tree(g,x,y){g.fillStyle(0x5b4027).fillRect(x-7,y,14,36);g.fillStyle(0x365e2e).fillRect(x-28,y-28,56,38);g.fillStyle(0x477838).fillRect(x-20,y-38,42,28);g.fillStyle(0x6b9a46).fillRect(x-12,y-31,20,8)}
createSolids(){this.solids=this.physics.add.staticGroup();const b=(x,y,w,h)=>{const z=this.add.zone(x+w/2,y+h/2,w,h);this.physics.add.existing(z,true);this.solids.add(z)};b(321,336,338,238);b(736,306,308,238);b(1086,586,298,218);if(!world.ashwoodUnlocked)b(1430,640,56,230)}
createPlayer(){this.player=this.add.container(900,760).setSize(30,46);this.physics.add.existing(this.player);this.player.body.setCollideWorldBounds(true).setSize(30,42).setOffset(-15,-21);this.physics.add.collider(this.player,this.solids);this.rebuildPlayer()}
rebuildPlayer(){this.player.removeAll(true);this.player.add(this.add.rectangle(0,20,28,7,0x000000,.22));this.legs=this.add.rectangle(0,12,20,18,0x71624f).setStrokeStyle(2,0x2a211d);this.bodyShape=this.add.rectangle(0,-5,22,22,0xd89a70).setStrokeStyle(2,0x2a211d);this.head=this.add.rectangle(0,-24,16,17,0xd89a70).setStrokeStyle(2,0x2a211d);this.player.add([this.legs,this.bodyShape,this.head]);if(state.equipped.armor)this.player.add(this.add.rectangle(0,-5,24,20,0x7f5639).setStrokeStyle(2,0x33271f));if(state.equipped.helmet)this.player.add(this.add.rectangle(0,-28,20,10,0xaeb6b8).setStrokeStyle(2,0x3a4042));if(state.equipped.weapon){this.player.add(this.add.rectangle(17,2,3,25,0x6d4b2f));this.player.add(this.add.rectangle(17,-10,7,15,0xc8d0d1))}if(state.equipped.shield)this.player.add(this.add.rectangle(-18,0,12,18,0x8a6038).setStrokeStyle(2,0x4d351f));if(state.equipped.boots){this.player.add(this.add.rectangle(-7,21,10,6,0x32281f));this.player.add(this.add.rectangle(7,21,10,6,0x32281f))}this.player.add(this.add.text(0,-45,"Hood",{fontFamily:"monospace",fontSize:"12px",color:"#f4ead2",fontStyle:"bold"}).setOrigin(.5))}
createNpcs(){this.bram=this.npc(1235,822,"OLD BRAM",0x5c4733);this.mara=this.npc(690,625,"MARA THE WARDEN",0x394d42);this.prompt=this.add.text(0,0,"",{fontFamily:"monospace",fontSize:"11px",color:"#f3e4bf",backgroundColor:"#10140ddd",padding:{x:8,y:5}}).setOrigin(.5).setDepth(50).setVisible(false)}npc(x,y,name,color){const c=this.add.container(x,y);c.add(this.add.rectangle(0,17,24,6,0x000000,.22));c.add(this.add.rectangle(0,-10,14,16,0xc4875e));c.add(this.add.rectangle(0,7,20,18,color));c.add(this.add.text(0,-32,name,{fontFamily:"monospace",fontSize:"10px",color:"#f3e4bf",fontStyle:"bold"}).setOrigin(.5));return c}
createControls(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys("W,A,S,D,E,I,ESC");this.input.keyboard.on("keydown-E",()=>this.interact());this.input.keyboard.on("keydown-I",()=>this.toggleInventory());this.input.keyboard.on("keydown-ESC",()=>this.closePanels())}
createUi(){this.shop=document.getElementById("pShop");this.inventory=document.getElementById("pInventory");document.getElementById("pShopClose").onclick=()=>this.closePanels();document.getElementById("pInvClose").onclick=()=>this.closePanels();document.getElementById("pInventoryBtn").onclick=()=>this.toggleInventory();this.renderShop();this.renderInventory()}
bindTouchControls(){const stop=e=>{e.preventDefault();e.stopPropagation()};document.querySelectorAll("[data-move]").forEach(btn=>{const d=btn.dataset.move,on=e=>{stop(e);this.touch[d]=true;btn.classList.add("active")},off=e=>{stop(e);this.touch[d]=false;btn.classList.remove("active")};btn.addEventListener("pointerdown",on);["pointerup","pointercancel","pointerleave"].forEach(ev=>btn.addEventListener(ev,off))});const action=(id,fn)=>document.getElementById(id)?.addEventListener("pointerdown",e=>{stop(e);fn()});action("mobileAttack",()=>this.combat?.attack());action("mobileInteract",()=>this.interact());action("mobileInventory",()=>this.toggleInventory());window.addEventListener("blur",()=>Object.keys(this.touch).forEach(k=>this.touch[k]=false))}
refreshHud(){document.getElementById("phaserCoins").textContent=`${state.coins} COINS`;const s=stats();document.getElementById("pStats").textContent=`HP ${s.hp} · ATK ${s.attack} · DEF ${s.defense} · SPD ${s.speed} · LUCK ${s.luck}`}
renderShop(){const root=document.getElementById("pShopItems");root.innerHTML="";ITEMS.forEach(it=>{const own=state.owned.has(it.id),eq=state.equipped[it.slot]===it.id,b=document.createElement("button");b.className="p-item";b.innerHTML=`<span><b>${it.name}</b><small>${it.rarity} · ${bonus(it)}</small></span><strong>${own?(eq?"EQUIPPED":"OWNED"):`${it.price} C`}</strong>`;b.onclick=()=>{if(own||state.coins<it.price)return;state.coins-=it.price;state.owned.add(it.id);if(!state.equipped[it.slot])state.equipped[it.slot]=it.id;save();this.rebuildPlayer();this.refreshHud();this.renderShop();this.renderInventory()};root.appendChild(b)})}
renderInventory(){const root=document.getElementById("pInvItems");root.innerHTML="";ITEMS.filter(it=>state.owned.has(it.id)).forEach(it=>{const eq=state.equipped[it.slot]===it.id,b=document.createElement("button");b.className="p-item";b.innerHTML=`<span><b>${it.name}</b><small>${it.slot.toUpperCase()} · ${bonus(it)}</small></span><strong>${eq?"UNEQUIP":"EQUIP"}</strong>`;b.onclick=()=>{state.equipped[it.slot]=eq?null:it.id;save();this.rebuildPlayer();this.refreshHud();this.renderInventory();this.renderShop()};root.appendChild(b)});const loot=window.HoodsProgression?.state?.loot||{};Object.entries(loot).filter(([,n])=>n>0).forEach(([name,n])=>{const d=document.createElement("div");d.className="p-item";d.innerHTML=`<span><b>${name}</b><small>WILDS DROP · MATERIAL</small></span><strong>×${n}</strong>`;root.appendChild(d)});if(!root.children.length)root.innerHTML='<p class="empty">No gear yet. Visit Old Bram.</p>'}
closePanels(){this.shop.hidden=true;this.inventory.hidden=true}toggleInventory(){const open=this.inventory.hidden;this.closePanels();this.inventory.hidden=!open;if(open)this.renderInventory()}
interact(){if(!this.shop.hidden||!this.inventory.hidden){this.closePanels();return}const db=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.bram.x,this.bram.y),dm=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.mara.x,this.mara.y);if(db<115){this.renderShop();this.shop.hidden=false}else if(dm<115)this.flash("Mara · quest migration is next",this.mara.x,this.mara.y-58)}flash(t,x,y){this.prompt.setText(t).setPosition(x,y).setVisible(true);this.time.delayedCall(1500,()=>this.prompt.setVisible(false))}
update(_,delta){const modal=!this.shop.hidden||!this.inventory.hidden,b=this.player.body;let dx=0,dy=0;if(!modal){if(this.cursors.left.isDown||this.keys.A.isDown||this.touch.left)dx--;if(this.cursors.right.isDown||this.keys.D.isDown||this.touch.right)dx++;if(this.cursors.up.isDown||this.keys.W.isDown||this.touch.up)dy--;if(this.cursors.down.isDown||this.keys.S.isDown||this.touch.down)dy++}const v=new Phaser.Math.Vector2(dx,dy);if(v.lengthSq())v.normalize().scale(185*(1+(stats().speed-5)*.03));b.setVelocity(v.x,v.y);const moving=v.lengthSq()>0;if(this.bodyShape){this.bodyShape.y=moving?-5+Math.sin(this.time.now/95):-5;this.head.y=moving?-24+Math.sin(this.time.now/95):-24}document.getElementById("phaserLocation").textContent=this.player.y<260?"THE WILDS":this.player.x>1480?"ASHWOOD TRAIL":this.player.x<500?"WEST GREEN":this.player.x>1320?"EAST GREEN":"TOWN SQUARE";const nb=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.bram.x,this.bram.y)<115,nm=Phaser.Math.Distance.Between(this.player.x,this.player.y,this.mara.x,this.mara.y)<115;if(!modal&&!this.prompt.visible&&(nb||nm)){const n=nm?this.mara:this.bram;this.prompt.setText("E · INTERACT").setPosition(n.x,n.y-58).setVisible(true)}else if(this.prompt.visible&&!nb&&!nm&&this.prompt.text==="E · INTERACT")this.prompt.setVisible(false);this.combat?.update(delta/1000)}
}
new Phaser.Game({type:Phaser.AUTO,parent:"phaser-root",width:960,height:600,backgroundColor:"#11160e",pixelArt:true,roundPixels:true,physics:{default:"arcade",arcade:{debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[TownScene]});
})();