// Hoods v0.9 — clean vertical slice: small town plaza, ordered HUD, shop, bag, quest and combat.
(() => {
const SAVE='hoods-v09';
const ITEMS=[
 {id:'sword',name:'Rusty Sword',slot:'weapon',price:25,atk:3},
 {id:'shield',name:'Wood Shield',slot:'shield',price:20,def:2},
 {id:'helmet',name:'Iron Hood',slot:'helmet',price:30,def:2},
 {id:'armor',name:'Leather Armor',slot:'armor',price:35,def:3,hp:15},
 {id:'boots',name:'Runner Boots',slot:'boots',price:22,spd:1}
];
const defState=()=>({coins:120,owned:['sword','shield'],gear:{weapon:'sword',shield:'shield',helmet:null,armor:null,boots:null},quest:{accepted:false,kills:0,done:false},loot:{ratTail:0}});
const load=()=>{try{return {...defState(),...(JSON.parse(localStorage.getItem(SAVE))||{})}}catch{return defState()}};
class Scene extends Phaser.Scene{
 constructor(){super('v09');this.s=load();this.touch={up:false,down:false,left:false,right:false};this.dir='down';this.walk=0;this.lastWalk=0;this.npcs=[];this.rats=[];this.mode='play';this.lastAtk=0;}
 preload(){const a='assets/v08/';['grass','cobble'].forEach(k=>this.load.svg(k,a+`tile-${k}.svg`));['tree','fountain','lamp','banner','barrel'].forEach(k=>this.load.svg(k,a+`prop-${k}.svg`));['bank','inn','shop'].forEach(k=>this.load.svg(k,a+`building-${k}.svg`));this.load.svg('hit',a+'hood-down.svg')}
 create(){this.W=1120;this.H=840;this.physics.world.setBounds(0,0,this.W,this.H);this.cameras.main.setBounds(0,0,this.W,this.H);this.cameras.main.setBackgroundColor('#23341f');this.buildPlaza();this.buildNpcs();this.buildHero();this.buildRats();this.buildHud();this.buildDom();this.keys=this.input.keyboard.addKeys('W,A,S,D,E,I,SPACE');this.cursors=this.input.keyboard.createCursorKeys();this.input.keyboard.on('keydown-E',()=>this.talk());this.input.keyboard.on('keydown-I',()=>this.openBag());this.input.keyboard.on('keydown-SPACE',()=>this.attack());this.bindMobile();this.cameras.main.startFollow(this.actor,true,.09,.09);this.setZoom();this.scale.on('resize',()=>this.setZoom());this.cameras.main.setRoundPixels(true);this.msg('Talk to Bram, buy gear, accept Mara quest, hunt rats east.');}
 save(){localStorage.setItem(SAVE,JSON.stringify(this.s));this.refreshHud();}
 stats(){let st={hp:125,atk:5,def:2,spd:170};Object.values(this.s.gear).filter(Boolean).forEach(id=>{const it=ITEMS.find(x=>x.id===id);if(!it)return;st.hp+=it.hp||0;st.atk+=it.atk||0;st.def+=it.def||0;st.spd+=it.spd?it.spd*12:0});return st;}
 buildPlaza(){const g=this.add.graphics();g.fillStyle(0x314b28,1).fillRect(0,0,this.W,this.H);for(let y=0;y<this.H;y+=32)for(let x=0;x<this.W;x+=32)this.add.image(x+16,y+16,'grass').setDepth(0);
 const tile=(x0,y0,w,h)=>{for(let y=y0;y<y0+h;y+=32)for(let x=x0;x<x0+w;x+=32)this.add.image(x+16,y+16,'cobble').setDepth(.2)};tile(290,0,530,this.H);tile(0,310,this.W,260);tile(220,210,680,470);
 const water=this.add.graphics().setDepth(.1);water.fillStyle(0x2b6688,1).fillRect(0,680,270,160).fillRect(850,680,270,160);water.lineStyle(2,0x6eb1cf,.65);for(let y=700;y<830;y+=24){water.beginPath();water.moveTo(0,y);water.lineTo(270,y+9);water.strokePath();water.beginPath();water.moveTo(850,y+6);water.lineTo(1120,y);water.strokePath()}
 this.bridge(220,720);this.bridge(900,720);
 this.add.image(250,280,'inn').setOrigin(.5,1).setScale(1.18).setDepth(34);this.add.image(560,245,'bank').setOrigin(.5,1).setScale(1.22).setDepth(32);this.add.image(850,285,'shop').setOrigin(.5,1).setScale(1.18).setDepth(34);
 this.add.image(560,480,'fountain').setScale(1.18).setDepth(58);this.garden(450,405);this.garden(670,405);this.garden(450,560);this.garden(670,560);
 [[90,120],[1030,120],[120,610],[1010,610],[355,150],[770,150],[350,690],[760,690],[985,430]].forEach(([x,y])=>this.add.image(x,y,'tree').setOrigin(.5,.9).setDepth(y/10));
 [[390,325],[730,325],[390,590],[730,590],[250,390],[850,395]].forEach(([x,y])=>this.add.image(x,y,'lamp').setOrigin(.5,1).setDepth(y/10+15));[[395,250],[725,250],[515,600],[605,600]].forEach(([x,y])=>this.add.image(x,y,'banner').setOrigin(.5,1).setDepth(y/10+12));[[315,560],[805,560],[210,610],[910,610],[185,350],[935,350]].forEach(([x,y])=>this.add.image(x,y,'barrel').setOrigin(.5,1).setDepth(y/10+10));
 const stall=this.add.graphics().setDepth(55);stall.fillStyle(0x5e442e,1).fillRoundedRect(65,500,155,75,6);['#e8dfc5','#5573a0','#e8dfc5','#5573a0','#e8dfc5'].forEach((c,i)=>{stall.fillStyle(Phaser.Display.Color.HexStringToColor(c).color,1).fillRect(65+i*31,480,31,24)});this.add.text(142,515,'MARKET',{fontFamily:'Georgia,serif',fontSize:'13px',color:'#f4d68c',stroke:'#1b130e',strokeThickness:3}).setOrigin(.5).setDepth(60);
 }
 bridge(x,y){const g=this.add.graphics().setDepth(y/10+8);g.fillStyle(0x65462f,1).fillRoundedRect(x-62,y-24,124,50,4);for(let i=-52;i<=52;i+=16)g.fillStyle(i%32?0x85603c:0x724d31,1).fillRect(x+i,y-22,12,44);g.lineStyle(3,0x302119,1).strokeRoundedRect(x-62,y-24,124,50,4)}
 garden(x,y){const g=this.add.graphics().setDepth(y/10+2);g.fillStyle(0x395c31,1).fillRoundedRect(x,y,100,42,8);g.lineStyle(3,0x6e6755,1).strokeRoundedRect(x,y,100,42,8);for(let yy=y+10;yy<y+37;yy+=13)for(let xx=x+12;xx<x+92;xx+=16){g.fillStyle([0xe4c45e,0xd87666,0xc58bd2,0xf4edd2][(xx+yy)%4],1).fillCircle(xx,yy,2.5)}}
 buildNpcs(){this.npc(250,345,'Sara','Innkeeper','Beds and rumors soon.');this.npc(560,305,'Thorn','Banker','Vault and wallet storage later.');this.npc(850,360,'Bram','Gear Merchant','I sell starter gear.');this.npc(765,545,'Mara','Quest Giver','Road East needs help. Take the rat contract.',true);this.npc(360,420,'Guard','Town Guard','Stay safe inside Hoods Town.');this.npc(140,590,'Merchant','Market','Consumables will go here.');}
 npc(x,y,name,role,line,quest=false){const c=this.add.container(x,y).setDepth(y/10+25);c.add(this.add.ellipse(0,19,28,8,0x0a0b09,.28));c.add(this.add.rectangle(0,6,22,31,quest?0x64413b:0x5b4a38).setStrokeStyle(2,0x211a16));c.add(this.add.rectangle(-10,6,6,20,0x3b3029));c.add(this.add.rectangle(10,6,6,20,0x3b3029));c.add(this.add.circle(0,-13,9,0xc38b68).setStrokeStyle(2,0x211a16));c.add(this.add.rectangle(0,-21,18,6,0x2b241f));c.add(this.add.text(0,-39,name,{fontFamily:'Georgia,serif',fontSize:'12px',fontStyle:'bold',color:'#f2e6c8',stroke:'#111',strokeThickness:4}).setOrigin(.5));if(quest)c.add(this.add.text(0,-60,'!',{fontFamily:'Georgia,serif',fontSize:'24px',fontStyle:'bold',color:'#ffd447',stroke:'#3b2509',strokeThickness:4}).setOrigin(.5));this.npcs.push({x,y,name,role,line});}
 buildHero(){this.actor=this.physics.add.sprite(560,585,'hit').setVisible(false).setCollideWorldBounds(true);this.actor.body.setSize(28,34).setOffset(10,27);this.shadow=this.add.ellipse(560,618,48,14,0x060806,.45);this.hero=this.add.container(560,585).setScale(1.24);this.name=this.add.text(560,520,'Hoods',{fontFamily:'Georgia,serif',fontSize:'15px',fontStyle:'bold',color:'#b9ef5a',stroke:'#142010',strokeThickness:4}).setOrigin(.5);this.drawHero(true);}
 drawHero(force=false){const key=this.dir+this.walk+JSON.stringify(this.s.gear);if(!force&&key===this.heroKey)return;this.heroKey=key;this.hero.removeAll(true);const R=(x,y,w,h,c,s=0x15110f)=>this.add.rectangle(x,y,w,h,c).setStrokeStyle(1,s);const side=this.dir==='left'?-1:this.dir==='right'?1:0,b=this.walk===1?-1:this.walk===3?1:0,step=this.walk===1?2:this.walk===3?-2:0,up=this.dir==='up',gear=this.s.gear;
 this.hero.add(R(-7,18+b+step,8,18,0x2b2725));this.hero.add(R(7,18+b-step,8,18,0x2b2725));this.hero.add(R(-8,29+b+step,13,6,gear.boots?0x0d0e0c:0x453328));this.hero.add(R(8,29+b-step,13,6,gear.boots?0x0d0e0c:0x453328));
 this.hero.add(R(0,2+b,29,29,0x1e1a18));this.hero.add(R(0,4+b,23,25,gear.armor?0x604538:0x75513c));if(gear.armor){this.hero.add(R(0,-4+b,22,5,0x95714e));this.hero.add(R(-8,7+b,5,17,0x3a332e));this.hero.add(R(8,7+b,5,17,0x3a332e))}this.hero.add(R(0,16+b,26,7,0x131110));
 this.hero.add(R(-18,0+b-step/2,7,23,0x46362d));this.hero.add(R(18,0+b+step/2,7,23,0x46362d));
 if(up){this.hero.add(R(0,-24+b,30,27,gear.helmet?0x6f797b:0x131211));this.hero.add(R(0,-19+b,20,16,0x29221f));this.hero.add(R(0,-13+b,14,8,0x443029));}
 else{this.hero.add(R(side*2,-24+b,30,26,gear.helmet?0x737d80:0x131211));this.hero.add(R(side*4,-20+b,21,18,0x29221f));this.hero.add(R(side*6,-12+b,15,10,0xc98b66));this.hero.add(R(side*10,-13+b,3,3,0x070707));this.hero.add(R(side*3,-8+b,7,2,0x704536));this.hero.add(R(-side*9,-16+b,6,15,0x131211));if(gear.helmet)this.hero.add(R(side*10,-20+b,8,5,0xc6cece,0x31383a));}
 this.hero.add(R(0,10+b,22,4,0x111));this.hero.add(R(0,12+b,5,5,0xb98a4e));
 if(this.dir!=='up'){if(gear.weapon){const wx=side?side*25:22,sword=this.add.container(wx,-3+b).setAngle(side?side*12:-8);sword.add(R(0,-2,4,29,0xcbd4d4,0x3d4446));sword.add(R(0,12,8,5,0x6b492d));this.hero.add(sword)}if(gear.shield){const sx=side?-side*23:-23;this.hero.add(R(sx,5+b,14,21,0x704d32,0x251b15));this.hero.add(R(sx,4+b,5,15,0xa67a48,0x251b15));}}
 }
 buildRats(){[[960,520],[1010,575],[930,640]].forEach((p,i)=>{const r=this.add.container(p[0],p[1]).setDepth(p[1]/10+25);r.hp=18;r.dead=false;r.add(this.add.ellipse(0,10,26,11,0x17110e));r.add(this.add.circle(-5,0,9,0x65523d).setStrokeStyle(2,0x2b2119));r.add(this.add.circle(5,0,8,0x756049).setStrokeStyle(2,0x2b2119));r.add(this.add.rectangle(9,-5,3,3,0x0a0807));r.add(this.add.text(0,-23,'Rat',{fontFamily:'monospace',fontSize:'9px',color:'#e8d3aa',stroke:'#111',strokeThickness:3}).setOrigin(.5));this.rats.push(r)})}
 buildHud(){this.ui=this.add.container(14,14).setScrollFactor(0).setDepth(700);const bg=this.add.graphics();bg.fillStyle(0x0b0d0b,.76).fillRoundedRect(0,0,218,88,10);bg.lineStyle(1,0x70624c,.8).strokeRoundedRect(0,0,218,88,10);this.ui.add(bg);this.ui.add(this.add.text(12,6,'Hoods',{fontFamily:'Georgia,serif',fontSize:'28px',fontStyle:'bold',color:'#f0d99a',stroke:'#111',strokeThickness:4}));this.hp=this.add.text(14,43,'',{fontFamily:'monospace',fontSize:'10px',color:'#fff',backgroundColor:'#792420',padding:{x:8,y:4}});this.gold=this.add.text(14,66,'',{fontFamily:'monospace',fontSize:'10px',color:'#f3d776'});this.ui.add([this.hp,this.gold]);this.questText=this.add.text(14,106,'',{fontFamily:'monospace',fontSize:'10px',color:'#b9ef5a',backgroundColor:'#0b0d0bcc',padding:{x:8,y:5}}).setScrollFactor(0).setDepth(700);this.hint=this.add.text(0,0,'',{fontFamily:'monospace',fontSize:'10px',color:'#f7efcf',backgroundColor:'#11140ddd',padding:{x:7,y:5}}).setOrigin(.5).setDepth(650);this.refreshHud();}
 refreshHud(){const st=this.stats();this.hp?.setText(`HP ${st.hp}/${st.hp}`);this.gold?.setText(`Coins ${this.s.coins} · Loot ${this.s.loot.ratTail}`);let q='Quest: talk to Mara';if(this.s.quest.accepted)q=this.s.quest.done?'Quest complete: Road East cleared':`Quest: hunt rats ${this.s.quest.kills}/3`;this.questText?.setText(q)}
 buildDom(){this.panel=document.createElement('div');this.panel.style.cssText='position:fixed;z-index:90;left:max(10px,env(safe-area-inset-left));right:max(10px,env(safe-area-inset-right));bottom:calc(86px + env(safe-area-inset-bottom));max-height:44vh;overflow:auto;background:#0b0d0bea;border:1px solid #75684e;border-radius:12px;padding:12px;color:#f4ecd2;font-family:Georgia,serif;display:none;box-shadow:0 10px 28px #0009';document.body.appendChild(this.panel)}
 panelHtml(title,body){this.panel.innerHTML=`<div style="font-size:18px;font-weight:800;color:#f2d58d;margin-bottom:4px">${title}</div>${body}<button id="closeP" style="margin-top:10px;width:100%;padding:10px;border-radius:8px;background:#171b15;border:1px solid #555;color:#eee">Close</button>`;this.panel.style.display='block';document.getElementById('closeP').onclick=()=>this.closePanel();}
 closePanel(){this.panel.style.display='none';this.mode='play'}
 talk(){if(this.panel.style.display==='block'){this.closePanel();return}const n=this.nearNpc();if(!n)return this.msg('Move closer to an NPC.');if(n.name==='Bram')return this.openShop();if(n.name==='Mara')return this.openMara();this.panelHtml(n.name,`<div style="font:700 10px monospace;color:#b9ef5a;margin-bottom:8px">${n.role}</div><div>${n.line}</div>`)}
 openShop(){this.mode='shop';let rows=ITEMS.map(it=>{const own=this.s.owned.includes(it.id),eq=this.s.gear[it.slot]===it.id;const txt=eq?'Equipped':own?'Equip':`Buy ${it.price}`;return `<button data-item="${it.id}" style="width:100%;margin:5px 0;padding:9px;border-radius:8px;background:#141911;border:1px solid #55624d;color:#f3e6c5;text-align:left"><b>${it.name}</b> · ${it.slot}<span style="float:right;color:#b9ef5a">${txt}</span></button>`}).join('');this.panelHtml('Old Bram\'s Gear',`<div style="font:700 10px monospace;color:#f3d776;margin-bottom:6px">Coins ${this.s.coins}</div>${rows}`);this.panel.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>this.buyOrEquip(b.dataset.item));}
 buyOrEquip(id){const it=ITEMS.find(x=>x.id===id);if(!it)return;if(!this.s.owned.includes(id)){if(this.s.coins<it.price)return this.msg('Not enough Coins.');this.s.coins-=it.price;this.s.owned.push(id);this.msg(`Bought ${it.name}`)}this.s.gear[it.slot]=this.s.gear[it.slot]===id?null:id;this.save();this.drawHero(true);this.openShop();}
 openBag(){let rows=ITEMS.filter(it=>this.s.owned.includes(it.id)).map(it=>`<button data-item="${it.id}" style="width:100%;margin:5px 0;padding:9px;border-radius:8px;background:#141911;border:1px solid #55624d;color:#f3e6c5;text-align:left">${this.s.gear[it.slot]===it.id?'✓ ':''}${it.name}<span style="float:right;color:#b9ef5a">${it.slot}</span></button>`).join('')||'<div>No items yet.</div>';this.panelHtml('Bag / Equipment',rows);this.panel.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{const it=ITEMS.find(x=>x.id===b.dataset.item);this.s.gear[it.slot]=this.s.gear[it.slot]===it.id?null:it.id;this.save();this.drawHero(true);this.openBag();});}
 openMara(){if(this.s.quest.done)return this.panelHtml('Mara','<div>Road East is safe for now. Take the reward and prepare for Ashwood later.</div>');if(!this.s.quest.accepted){this.panelHtml('Mara',`<div>Rats are blocking Road East. Hunt 3 rats and return stronger.</div><button id="acceptQ" style="margin-top:10px;width:100%;padding:10px;border-radius:8px;background:#26351f;border:1px solid #b9ef5a;color:#b9ef5a;font-weight:900">Accept quest</button>`);document.getElementById('acceptQ').onclick=()=>{this.s.quest.accepted=true;this.save();this.closePanel();this.msg('Quest accepted: hunt 3 rats.')}}else this.panelHtml('Mara',`<div>Road East progress: ${this.s.quest.kills}/3 rats.</div>`)}
 nearNpc(){let best=null,bd=999;this.npcs.forEach(n=>{const d=Phaser.Math.Distance.Between(this.actor.x,this.actor.y,n.x,n.y);if(d<bd){bd=d;best=n}});return bd<95?best:null}
 attack(){const now=this.time.now;if(now-this.lastAtk<350)return;this.lastAtk=now;let target=null,bd=999;this.rats.forEach(r=>{if(r.dead)return;const d=Phaser.Math.Distance.Between(this.actor.x,this.actor.y,r.x,r.y);if(d<bd){bd=d;target=r}});if(!target||bd>92)return this.msg('No enemy in range.');target.hp-=this.stats().atk;this.hitFx(target.x,target.y,`-${this.stats().atk}`);if(target.hp<=0)this.killRat(target);}
 killRat(r){r.dead=true;r.setVisible(false);this.s.coins+=8;this.s.loot.ratTail++;if(this.s.quest.accepted&&!this.s.quest.done){this.s.quest.kills++;if(this.s.quest.kills>=3){this.s.quest.done=true;this.s.coins+=40;this.msg('Quest complete +40 Coins')}}this.save();this.time.delayedCall(4500,()=>{r.hp=18;r.dead=false;r.setVisible(true)})}
 hitFx(x,y,t){const txt=this.add.text(x,y-28,t,{fontFamily:'monospace',fontSize:'13px',fontStyle:'bold',color:'#ffef9f',stroke:'#250e0a',strokeThickness:3}).setOrigin(.5).setDepth(800);this.tweens.add({targets:txt,y:y-55,alpha:0,duration:550,onComplete:()=>txt.destroy()})}
 msg(t){this.toast?.destroy();this.toast=this.add.text(this.actor?.x||560,(this.actor?.y||585)-82,t,{fontFamily:'monospace',fontSize:'10px',color:'#f6edc9',backgroundColor:'#10140ddd',padding:{x:7,y:5},wordWrap:{width:260}}).setOrigin(.5).setDepth(800);this.time.delayedCall(1600,()=>this.toast?.destroy())}
 bindMobile(){const hold=(sel,key)=>{document.querySelectorAll(sel).forEach(btn=>{const on=e=>{e.preventDefault();this.touch[key]=true;btn.classList.add('active')},off=e=>{e.preventDefault();this.touch[key]=false;btn.classList.remove('active')};btn.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,off))})};['up','down','left','right'].forEach(k=>hold(`[data-move="${k}"]`,k));document.getElementById('talkBtn')?.addEventListener('click',e=>{e.preventDefault();this.talk()});document.getElementById('bagBtn')?.addEventListener('click',e=>{e.preventDefault();this.openBag()});document.getElementById('atkBtn')?.addEventListener('click',e=>{e.preventDefault();this.attack()});}
 setZoom(){const w=this.scale.width;this.cameras.main.setZoom(w<500?.72:w<850?.86:1.05)}
 update(time){let dx=0,dy=0;if(this.cursors.left.isDown||this.keys.A.isDown||this.touch.left)dx--;if(this.cursors.right.isDown||this.keys.D.isDown||this.touch.right)dx++;if(this.cursors.up.isDown||this.keys.W.isDown||this.touch.up)dy--;if(this.cursors.down.isDown||this.keys.S.isDown||this.touch.down)dy++;const moving=!!(dx||dy);if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;if(Math.abs(dx)>Math.abs(dy))this.dir=dx<0?'left':'right';else this.dir=dy<0?'up':'down';if(time-this.lastWalk>105){this.walk=(this.walk+1)%4;this.lastWalk=time}}else this.walk=0;this.actor.setVelocity(dx*this.stats().spd,dy*this.stats().spd);this.hero.setPosition(Math.round(this.actor.x),Math.round(this.actor.y));this.shadow.setPosition(this.actor.x,this.actor.y+33);this.drawHero();this.hero.setDepth(this.actor.y/10+45);this.shadow.setDepth(this.hero.depth-1);this.name.setPosition(this.actor.x,this.actor.y-66).setDepth(this.hero.depth+1);const n=this.nearNpc();this.hint.setText(n?`TALK ${n.name}`:'').setPosition(this.actor.x,this.actor.y-88).setVisible(!!n)}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',pixelArt:true,roundPixels:true,backgroundColor:'#23341f',physics:{default:'arcade',arcade:{debug:false}},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH,width:window.innerWidth,height:window.innerHeight},scene:Scene});
})();