// Hoods v0.9.1 — cleaner visual slice: tighter plaza, cleaner HUD, reusable systems.
(() => {
const SAVE='hoods-v091';
const ITEMS=[
 {id:'sword',name:'Rusty Sword',slot:'weapon',price:25,atk:3,icon:'⚔'},
 {id:'shield',name:'Wood Shield',slot:'shield',price:20,def:2,icon:'🛡'},
 {id:'helmet',name:'Iron Hood',slot:'helmet',price:30,def:2,icon:'⛑'},
 {id:'armor',name:'Leather Armor',slot:'armor',price:35,def:3,hp:15,icon:'▣'},
 {id:'boots',name:'Runner Boots',slot:'boots',price:22,spd:1,icon:'▥'}
];
const fresh=()=>({coins:120,owned:['sword','shield'],gear:{weapon:'sword',shield:'shield',helmet:null,armor:null,boots:null},quest:{accepted:false,kills:0,done:false},loot:{ratTail:0}});
const load=()=>{try{return {...fresh(),...(JSON.parse(localStorage.getItem(SAVE))||{})}}catch{return fresh()}};
class Game extends Phaser.Scene{
 constructor(){super('v091');this.s=load();this.touch={up:false,down:false,left:false,right:false};this.dir='down';this.walk=0;this.lastWalk=0;this.npcs=[];this.rats=[];this.mode='play';this.lastAtk=0;this.heroKey='';}
 preload(){const a='assets/v08/';['grass','cobble'].forEach(k=>this.load.svg(k,a+`tile-${k}.svg`));['tree','fountain','lamp','banner','barrel'].forEach(k=>this.load.svg(k,a+`prop-${k}.svg`));['bank','inn','shop'].forEach(k=>this.load.svg(k,a+`building-${k}.svg`));this.load.svg('hit',a+'hood-down.svg');}
 create(){this.W=980;this.H=720;this.physics.world.setBounds(0,0,this.W,this.H);this.cameras.main.setBounds(0,0,this.W,this.H);this.cameras.main.setBackgroundColor('#22341f');this.makeWorld();this.makeNpcs();this.makeHero();this.makeRats();this.makeHud();this.makeDom();this.keys=this.input.keyboard.addKeys('W,A,S,D,E,I,SPACE');this.cursors=this.input.keyboard.createCursorKeys();this.input.keyboard.on('keydown-E',()=>this.talk());this.input.keyboard.on('keydown-I',()=>this.openBag());this.input.keyboard.on('keydown-SPACE',()=>this.attack());this.bindMobile();this.cameras.main.startFollow(this.actor,true,.09,.09);this.setZoom();this.scale.on('resize',()=>this.setZoom());this.cameras.main.setRoundPixels(true);this.msg('Mara has work. Bram sells starter gear. Rats are east.');}
 save(){localStorage.setItem(SAVE,JSON.stringify(this.s));this.refreshHud();}
 stats(){let st={hp:125,atk:5,def:2,spd:166};Object.values(this.s.gear).filter(Boolean).forEach(id=>{const it=ITEMS.find(x=>x.id===id);if(!it)return;st.hp+=it.hp||0;st.atk+=it.atk||0;st.def+=it.def||0;st.spd+=(it.spd||0)*12});return st;}
 makeWorld(){const W=this.W,H=this.H;for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32)this.add.image(x+16,y+16,'grass').setDepth(0);
  const cob=(x,y,w,h)=>{for(let yy=y;yy<y+h;yy+=32)for(let xx=x;xx<x+w;xx+=32)this.add.image(xx+16,yy+16,'cobble').setDepth(.2)};
  cob(300,0,380,H);cob(0,280,W,210);cob(230,190,520,395);
  const edge=this.add.graphics().setDepth(.35);edge.lineStyle(4,0x4f4b40,1);edge.strokeRoundedRect(230,190,520,395,8);edge.strokeRoundedRect(300,0,380,H,0);edge.strokeRoundedRect(0,280,W,210,0);
  const water=this.add.graphics().setDepth(.12);water.fillStyle(0x2e6b8e,1).fillRoundedRect(0,585,235,135,10).fillRoundedRect(790,585,190,135,10);water.lineStyle(2,0x73b8d6,.65);for(let y=600;y<710;y+=22){water.beginPath();water.moveTo(0,y);water.lineTo(235,y+7);water.strokePath();water.beginPath();water.moveTo(790,y+5);water.lineTo(980,y);water.strokePath()}
  this.bridge(205,615);this.bridge(810,615);this.building(185,250,'inn','The Rusty Sword',1.02);this.building(490,230,'bank','Bank',1.05);this.building(790,255,'shop',"Old Bram's",1.02);
  this.add.image(490,430,'fountain').setDepth(58).setScale(1.08);this.garden(370,360);this.garden(560,360);this.garden(370,510);this.garden(560,510);
  [[70,120],[910,115],[90,510],[880,480],[250,120],[730,125],[300,615],[705,610],[910,330]].forEach(([x,y])=>this.add.image(x,y,'tree').setOrigin(.5,.9).setDepth(y/10));
  [[325,292],[655,292],[325,535],[655,535],[190,335],[790,340]].forEach(([x,y])=>this.add.image(x,y,'lamp').setOrigin(.5,1).setDepth(y/10+15));
  [[330,225],[650,225],[445,540],[535,540]].forEach(([x,y])=>this.add.image(x,y,'banner').setOrigin(.5,1).setDepth(y/10+12));
  [[260,505],[725,505],[140,520],[850,520],[145,315],[835,315]].forEach(([x,y])=>this.add.image(x,y,'barrel').setOrigin(.5,1).setDepth(y/10+10));
 }
 building(x,y,key,label,scale){const sh=this.add.graphics().setDepth(y/10+8);sh.fillStyle(0x000000,.24).fillRoundedRect(x-112*scale,y-28,224*scale,38,6);this.add.image(x,y,key).setOrigin(.5,1).setScale(scale).setDepth(y/10+18);this.add.text(x,y-118*scale,label,{fontFamily:'Georgia,serif',fontSize:'15px',fontStyle:'bold',color:'#f1d99a',stroke:'#1a110c',strokeThickness:4}).setOrigin(.5).setDepth(y/10+24)}
 bridge(x,y){const g=this.add.graphics().setDepth(y/10+8);g.fillStyle(0x67472e,1).fillRoundedRect(x-54,y-20,108,43,4);for(let i=-45;i<=45;i+=15)g.fillStyle(i%30?0x86613d:0x724f34,1).fillRect(x+i,y-18,11,39);g.lineStyle(3,0x302119,1).strokeRoundedRect(x-54,y-20,108,43,4)}
 garden(x,y){const g=this.add.graphics().setDepth(y/10+2);g.fillStyle(0x375b30,1).fillRoundedRect(x,y,82,36,8);g.lineStyle(3,0x6f6654,1).strokeRoundedRect(x,y,82,36,8);for(let yy=y+9;yy<y+32;yy+=11)for(let xx=x+10;xx<x+75;xx+=14)g.fillStyle([0xe2c45c,0xd87868,0xc88bd2,0xf3ecd2][(xx+yy)%4],1).fillCircle(xx,yy,2.3)}
 makeNpcs(){this.npc(185,308,'Sara','Innkeeper','Rooms and rumors soon.');this.npc(490,292,'Thorn','Banker','Vault storage will open here.');this.npc(790,322,'Bram','Gear Merchant','Buy, equip and survive.');this.npc(700,490,'Mara','Quest Giver','Road East: clear three rats.',true);this.npc(315,385,'Guard','Town Guard','Safe zone ends at the east road.');this.npc(130,530,'Merchant','Market','Consumables later.');}
 npc(x,y,name,role,line,quest=false){const c=this.add.container(x,y).setDepth(y/10+25);c.add(this.add.ellipse(0,19,28,8,0x0a0b09,.28));c.add(this.add.rectangle(0,7,22,31,quest?0x684039:0x594837).setStrokeStyle(2,0x211a16));c.add(this.add.rectangle(-10,7,6,21,0x3b3029));c.add(this.add.rectangle(10,7,6,21,0x3b3029));c.add(this.add.circle(0,-12,9,0xc38b68).setStrokeStyle(2,0x211a16));c.add(this.add.rectangle(0,-20,18,6,0x2b241f));c.add(this.add.text(0,-38,name,{fontFamily:'Georgia,serif',fontSize:'12px',fontStyle:'bold',color:'#f2e6c8',stroke:'#111',strokeThickness:4}).setOrigin(.5));if(quest)c.add(this.add.text(0,-58,'!',{fontFamily:'Georgia,serif',fontSize:'24px',fontStyle:'bold',color:'#ffd447',stroke:'#3b2509',strokeThickness:4}).setOrigin(.5));this.npcs.push({x,y,name,role,line});}
 makeHero(){this.actor=this.physics.add.sprite(490,505,'hit').setVisible(false).setCollideWorldBounds(true);this.actor.body.setSize(28,34).setOffset(10,27);this.shadow=this.add.ellipse(490,538,48,14,0x060806,.45);this.hero=this.add.container(490,505).setScale(1.22);this.name=this.add.text(490,444,'Hoods',{fontFamily:'Georgia,serif',fontSize:'15px',fontStyle:'bold',color:'#b9ef5a',stroke:'#142010',strokeThickness:4}).setOrigin(.5);this.drawHero(true);}
 drawHero(force=false){const key=this.dir+this.walk+JSON.stringify(this.s.gear);if(!force&&key===this.heroKey)return;this.heroKey=key;this.hero.removeAll(true);const R=(x,y,w,h,c,s=0x15110f)=>this.add.rectangle(x,y,w,h,c).setStrokeStyle(1,s);const side=this.dir==='left'?-1:this.dir==='right'?1:0,b=this.walk===1?-1:this.walk===3?1:0,step=this.walk===1?2:this.walk===3?-2:0,up=this.dir==='up',gear=this.s.gear;
  this.hero.add(R(-7,18+b+step,8,18,0x2b2725));this.hero.add(R(7,18+b-step,8,18,0x2b2725));this.hero.add(R(-8,29+b+step,13,6,gear.boots?0x0d0e0c:0x453328));this.hero.add(R(8,29+b-step,13,6,gear.boots?0x0d0e0c:0x453328));this.hero.add(R(0,2+b,29,29,0x1e1a18));this.hero.add(R(0,4+b,23,25,gear.armor?0x604538:0x75513c));
  if(gear.armor){this.hero.add(R(0,-4+b,22,5,0x95714e));this.hero.add(R(-8,7+b,5,17,0x3a332e));this.hero.add(R(8,7+b,5,17,0x3a332e))}this.hero.add(R(0,16+b,26,7,0x131110));this.hero.add(R(-18,0+b-step/2,7,23,0x46362d));this.hero.add(R(18,0+b+step/2,7,23,0x46362d));
  if(up){this.hero.add(R(0,-24+b,30,27,gear.helmet?0x6f797b:0x131211));this.hero.add(R(0,-19+b,20,16,0x29221f));this.hero.add(R(0,-13+b,14,8,0x443029));}
  else{this.hero.add(R(side*2,-24+b,30,26,gear.helmet?0x737d80:0x131211));this.hero.add(R(side*4,-20+b,21,18,0x29221f));this.hero.add(R(side*6,-12+b,15,10,0xc98b66));this.hero.add(R(side*10,-13+b,3,3,0x070707));this.hero.add(R(side*3,-8+b,7,2,0x704536));this.hero.add(R(-side*9,-16+b,6,15,0x131211));if(gear.helmet)this.hero.add(R(side*10,-20+b,8,5,0xc6cece,0x31383a));}
  this.hero.add(R(0,10+b,22,4,0x111));this.hero.add(R(0,12+b,5,5,0xb98a4e));if(this.dir!=='up'){if(gear.weapon){const wx=side?side*25:22,sword=this.add.container(wx,-3+b).setAngle(side?side*12:-8);sword.add(R(0,-2,4,29,0xcbd4d4,0x3d4446));sword.add(R(0,12,8,5,0x6b492d));this.hero.add(sword)}if(gear.shield){const sx=side?-side*23:-23;this.hero.add(R(sx,5+b,14,21,0x704d32,0x251b15));this.hero.add(R(sx,4+b,5,15,0xa67a48,0x251b15));}}
 }
 makeRats(){[[830,460],[880,515],[820,570]].forEach(([x,y])=>{const r=this.add.container(x,y).setDepth(y/10+25);r.hp=18;r.dead=false;r.add(this.add.ellipse(0,10,26,11,0x17110e));r.add(this.add.circle(-5,0,9,0x65523d).setStrokeStyle(2,0x2b2119));r.add(this.add.circle(5,0,8,0x756049).setStrokeStyle(2,0x2b2119));r.add(this.add.rectangle(9,-5,3,3,0x0a0807));r.add(this.add.text(0,-23,'Rat',{fontFamily:'monospace',fontSize:'9px',color:'#e8d3aa',stroke:'#111',strokeThickness:3}).setOrigin(.5));this.rats.push(r)})}
 makeHud(){this.ui=this.add.container(10,10).setScrollFactor(0).setDepth(700);const bg=this.add.graphics();bg.fillStyle(0x0b0d0b,.72).fillRoundedRect(0,0,168,62,9);bg.lineStyle(1,0x70624c,.8).strokeRoundedRect(0,0,168,62,9);this.ui.add(bg);this.ui.add(this.add.text(10,3,'Hoods',{fontFamily:'Georgia,serif',fontSize:'22px',fontStyle:'bold',color:'#f0d99a',stroke:'#111',strokeThickness:4}));this.hp=this.add.text(12,35,'',{fontFamily:'monospace',fontSize:'9px',color:'#fff'});this.gold=this.add.text(12,48,'',{fontFamily:'monospace',fontSize:'9px',color:'#f3d776'});this.ui.add([this.hp,this.gold]);this.questText=this.add.text(10,78,'',{fontFamily:'monospace',fontSize:'9px',color:'#b9ef5a',backgroundColor:'#0b0d0bcc',padding:{x:6,y:4}}).setScrollFactor(0).setDepth(700);this.hint=this.add.text(0,0,'',{fontFamily:'monospace',fontSize:'10px',color:'#f7efcf',backgroundColor:'#11140ddd',padding:{x:7,y:5}}).setOrigin(.5).setDepth(650);this.refreshHud();}
 refreshHud(){const st=this.stats();this.hp?.setText(`HP ${st.hp}/${st.hp}`);this.gold?.setText(`Coins ${this.s.coins} · Loot ${this.s.loot.ratTail}`);let q='Quest: talk to Mara';if(this.s.quest.accepted)q=this.s.quest.done?'Quest complete':`Quest: rats ${this.s.quest.kills}/3`;this.questText?.setText(q)}
 makeDom(){const box=document.createElement('div');box.id='dialogueBox';box.style.cssText='position:fixed;left:12px;right:12px;bottom:calc(92px + env(safe-area-inset-bottom));z-index:80;background:#0b0e0bea;border:1px solid #6f7a62;border-radius:12px;padding:12px;color:#f4eed4;font-family:Georgia,serif;box-shadow:0 8px 28px #0008;display:none';box.innerHTML='<b id="dTitle" style="color:#f0d79d;font-size:16px"></b><div id="dRole" style="font:700 10px monospace;color:#b9ef5a;margin:2px 0 8px"></div><div id="dLine" style="font-size:14px;line-height:1.3"></div><div id="dItems" style="display:grid;gap:6px;margin-top:10px"></div><button id="dClose" style="margin-top:8px;width:100%;padding:10px;border-radius:8px;background:#171b15;color:#eee;border:1px solid #555">Close</button>';document.body.appendChild(box);this.box=box;document.getElementById('dClose').onclick=()=>this.closeBox();}
 openBox(title,role,line,items=[]){this.mode='menu';this.box.style.display='block';document.getElementById('dTitle').textContent=title;document.getElementById('dRole').textContent=role;document.getElementById('dLine').textContent=line;const el=document.getElementById('dItems');el.innerHTML='';items.forEach(it=>{const b=document.createElement('button');b.textContent=it.label;b.style.cssText='padding:10px;border-radius:8px;background:#26351f;color:#b9ef5a;border:1px solid #8b947f;font-weight:800';b.onclick=it.fn;el.appendChild(b)})}
 closeBox(){this.box.style.display='none';this.mode='play'}
 nearNpc(){let best=null,bd=999;for(const n of this.npcs){const d=Phaser.Math.Distance.Between(this.actor.x,this.actor.y,n.x,n.y);if(d<bd){bd=d;best=n}}return bd<82?best:null}
 talk(){if(this.mode==='menu'){this.closeBox();return}const n=this.nearNpc();if(!n)return;if(n.name==='Bram')this.shop();else if(n.name==='Mara')this.mara();else this.openBox(n.name,n.role,n.line)}
 shop(){this.openBox('Bram','Gear merchant','Starter gear. Buy once, equip from Bag.',ITEMS.map(it=>({label:`${it.icon} ${it.name} · ${it.price} Coins`,fn:()=>{if(this.s.owned.includes(it.id)){this.msg('Already owned. Open Bag.');return}if(this.s.coins<it.price){this.msg('Not enough Coins.');return}this.s.coins-=it.price;this.s.owned.push(it.id);this.s.gear[it.slot]=it.id;this.save();this.drawHero(true);this.msg(`Bought ${it.name}`)}})))}
 mara(){if(this.s.quest.done){this.openBox('Mara','Quest giver','Road East is safe for now. More work soon.');return}if(!this.s.quest.accepted)this.openBox('Mara','Quest giver','Clear three rats east of town.',[{label:'Accept quest',fn:()=>{this.s.quest.accepted=true;this.save();this.closeBox();this.msg('Quest accepted: hunt 3 rats.')}}]);else this.openBox('Mara','Quest giver',`Progress: ${this.s.quest.kills}/3 rats.`)}
 openBag(){const rows=this.s.owned.map(id=>{const it=ITEMS.find(x=>x.id===id);const on=this.s.gear[it.slot]===id;return{label:`${on?'✓':'□'} ${it.icon} ${it.name}`,fn:()=>{this.s.gear[it.slot]=on?null:id;this.save();this.drawHero(true);this.openBag();}}});this.openBox('Bag','Inventory','Equip or unequip owned gear.',rows)}
 attack(){if(this.mode==='menu')return;const now=this.time.now;if(now-this.lastAtk<380)return;this.lastAtk=now;let hit=null,bd=999;for(const r of this.rats.filter(x=>!x.dead)){const d=Phaser.Math.Distance.Between(this.actor.x,this.actor.y,r.x,r.y);if(d<bd){bd=d;hit=r}}if(!hit||bd>82){this.msg('No enemy in range.');return}hit.hp-=this.stats().atk;hit.setAlpha(.55);this.time.delayedCall(90,()=>hit.setAlpha(1));if(hit.hp<=0){hit.dead=true;hit.setVisible(false);this.s.coins+=8;this.s.loot.ratTail++;if(this.s.quest.accepted&&!this.s.quest.done){this.s.quest.kills++;if(this.s.quest.kills>=3){this.s.quest.done=true;this.s.coins+=35;this.msg('Quest complete +35 Coins');}}this.save();this.time.delayedCall(5000,()=>{hit.hp=18;hit.dead=false;hit.setVisible(true)})}}
 msg(t){this.toast?.destroy();this.toast=this.add.text(this.actor?.x||490,(this.actor?.y||505)-82,t,{fontFamily:'monospace',fontSize:'10px',color:'#f4e7b5',backgroundColor:'#11140ddd',padding:{x:7,y:5}}).setOrigin(.5).setDepth(800);this.time.delayedCall(1800,()=>this.toast?.destroy())}
 bindMobile(){document.querySelectorAll('[data-move]').forEach(btn=>{const d=btn.dataset.move,on=e=>{e.preventDefault();this.touch[d]=true;btn.classList.add('active')},off=e=>{e.preventDefault();this.touch[d]=false;btn.classList.remove('active')};btn.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave'].forEach(ev=>btn.addEventListener(ev,off))});document.getElementById('talkBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();this.talk()});document.getElementById('bagBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();this.openBag()});document.getElementById('atkBtn')?.addEventListener('pointerdown',e=>{e.preventDefault();this.attack()});}
 setZoom(){const w=this.scale.width;this.cameras.main.setZoom(w<500?.72:w<800?.84:1.05)}
 update(time){let dx=0,dy=0;if(this.mode!=='menu'){if(this.cursors.left.isDown||this.keys.A.isDown||this.touch.left)dx--;if(this.cursors.right.isDown||this.keys.D.isDown||this.touch.right)dx++;if(this.cursors.up.isDown||this.keys.W.isDown||this.touch.up)dy--;if(this.cursors.down.isDown||this.keys.S.isDown||this.touch.down)dy++;}const moving=!!(dx||dy);if(moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;if(Math.abs(dx)>Math.abs(dy))this.dir=dx<0?'left':'right';else this.dir=dy<0?'up':'down';if(time-this.lastWalk>110){this.walk=(this.walk+1)%4;this.lastWalk=time}}else this.walk=0;this.actor.setVelocity(dx*this.stats().spd,dy*this.stats().spd);this.actor.setPosition(Math.round(this.actor.x),Math.round(this.actor.y));this.hero.setPosition(this.actor.x,this.actor.y);this.shadow.setPosition(this.actor.x,this.actor.y+32);this.drawHero();this.hero.setDepth(this.actor.y/10+35);this.shadow.setDepth(this.hero.depth-1);this.name.setPosition(this.actor.x,this.actor.y-62).setDepth(this.hero.depth+1);const n=this.nearNpc();this.hint.setVisible(!!n&&this.mode==='play');if(n)this.hint.setText(`TALK ${n.name}`).setPosition(n.x,n.y-58)}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',backgroundColor:'#22341f',pixelArt:true,roundPixels:true,physics:{default:'arcade',arcade:{debug:false}},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH,width:window.innerWidth,height:window.innerHeight},scene:Game});
})();